apiVersion: sailoperator.io/v1alpha1
kind: IstioCNI
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: v1.24.3
  namespace: istio-system
  profile: ambient
