apiVersion: batch/v1
kind: Job
metadata:
  name: step2-ossm-config-enable
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      containers:
        - name: oc
          image: quay.io/openshift/origin-cli:4.16
          command:
            - /bin/sh
            - -ec
          args:
            - |
              oc patch namespace eshoplite-vm --type=merge -p '{"metadata":{"labels":{"istio-injection":"enabled"}}}'
              oc patch vm eshoplite-vm -n eshoplite-vm --type=merge -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true","traffic.sidecar.istio.io/kubevirtInterfaces":"k6t-eth0"}}}}}'